package com.sz.entity;

public class Items {

    @Override
    public String toString() {
        return "Items{" +
                "eid=" + eid +
                ", ename='" + ename + '\'' +
                ", epaperid=" + epaperid +
                ", escore=" + escore +
                ", etype=" + etype +
                ", edegree=" + edegree +
                ", ea='" + ea + '\'' +
                ", eb='" + eb + '\'' +
                ", ec='" + ec + '\'' +
                ", ed='" + ed + '\'' +
                ", ee='" + ee + '\'' +
                ", ey='" + ey + '\'' +
                ", ekeys='" + ekeys + '\'' +
                ", ehints='" + ehints + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.epaperid
     *
     * @mbggenerated
     */
    private Integer epaperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.escore
     *
     * @mbggenerated
     */
    private Integer escore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.etype
     *
     * @mbggenerated
     */
    private Integer etype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.edegree
     *
     * @mbggenerated
     */
    private Integer edegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ea
     *
     * @mbggenerated
     */
    private String ea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.eb
     *
     * @mbggenerated
     */
    private String eb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ec
     *
     * @mbggenerated
     */
    private String ec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ed
     *
     * @mbggenerated
     */
    private String ed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ee
     *
     * @mbggenerated
     */
    private String ee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ey
     *
     * @mbggenerated
     */
    private String ey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ekeys
     *
     * @mbggenerated
     */
    private String ekeys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ehints
     *
     * @mbggenerated
     */
    private String ehints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.eid
     *
     * @return the value of items.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.eid
     *
     * @param eid the value for items.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ename
     *
     * @return the value of items.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ename
     *
     * @param ename the value for items.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.epaperid
     *
     * @return the value of items.epaperid
     *
     * @mbggenerated
     */
    public Integer getEpaperid() {
        return epaperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.epaperid
     *
     * @param epaperid the value for items.epaperid
     *
     * @mbggenerated
     */
    public void setEpaperid(Integer epaperid) {
        this.epaperid = epaperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.escore
     *
     * @return the value of items.escore
     *
     * @mbggenerated
     */
    public Integer getEscore() {
        return escore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.escore
     *
     * @param escore the value for items.escore
     *
     * @mbggenerated
     */
    public void setEscore(Integer escore) {
        this.escore = escore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.etype
     *
     * @return the value of items.etype
     *
     * @mbggenerated
     */
    public Integer getEtype() {
        return etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.etype
     *
     * @param etype the value for items.etype
     *
     * @mbggenerated
     */
    public void setEtype(Integer etype) {
        this.etype = etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.edegree
     *
     * @return the value of items.edegree
     *
     * @mbggenerated
     */
    public Integer getEdegree() {
        return edegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.edegree
     *
     * @param edegree the value for items.edegree
     *
     * @mbggenerated
     */
    public void setEdegree(Integer edegree) {
        this.edegree = edegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ea
     *
     * @return the value of items.ea
     *
     * @mbggenerated
     */
    public String getEa() {
        return ea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ea
     *
     * @param ea the value for items.ea
     *
     * @mbggenerated
     */
    public void setEa(String ea) {
        this.ea = ea == null ? null : ea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.eb
     *
     * @return the value of items.eb
     *
     * @mbggenerated
     */
    public String getEb() {
        return eb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.eb
     *
     * @param eb the value for items.eb
     *
     * @mbggenerated
     */
    public void setEb(String eb) {
        this.eb = eb == null ? null : eb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ec
     *
     * @return the value of items.ec
     *
     * @mbggenerated
     */
    public String getEc() {
        return ec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ec
     *
     * @param ec the value for items.ec
     *
     * @mbggenerated
     */
    public void setEc(String ec) {
        this.ec = ec == null ? null : ec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ed
     *
     * @return the value of items.ed
     *
     * @mbggenerated
     */
    public String getEd() {
        return ed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ed
     *
     * @param ed the value for items.ed
     *
     * @mbggenerated
     */
    public void setEd(String ed) {
        this.ed = ed == null ? null : ed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ee
     *
     * @return the value of items.ee
     *
     * @mbggenerated
     */
    public String getEe() {
        return ee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ee
     *
     * @param ee the value for items.ee
     *
     * @mbggenerated
     */
    public void setEe(String ee) {
        this.ee = ee == null ? null : ee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ey
     *
     * @return the value of items.ey
     *
     * @mbggenerated
     */
    public String getEy() {
        return ey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ey
     *
     * @param ey the value for items.ey
     *
     * @mbggenerated
     */
    public void setEy(String ey) {
        this.ey = ey == null ? null : ey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ekeys
     *
     * @return the value of items.ekeys
     *
     * @mbggenerated
     */
    public String getEkeys() {
        return ekeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ekeys
     *
     * @param ekeys the value for items.ekeys
     *
     * @mbggenerated
     */
    public void setEkeys(String ekeys) {
        this.ekeys = ekeys == null ? null : ekeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ehints
     *
     * @return the value of items.ehints
     *
     * @mbggenerated
     */
    public String getEhints() {
        return ehints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.ehints
     *
     * @param ehints the value for items.ehints
     *
     * @mbggenerated
     */
    public void setEhints(String ehints) {
        this.ehints = ehints == null ? null : ehints.trim();
    }
}