package com.sz.entity;

public class Papers {

    @Override
    public String toString() {
        return "Papers{" +
                "paperid=" + paperid +
                ", papernames='" + papernames + '\'' +
                ", papertype='" + papertype + '\'' +
                ", method='" + method + '\'' +
                ", remarks='" + remarks + '\'' +
                ", createtime='" + createtime + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column papers.paperid
     *
     * @mbggenerated
     */
    private Integer paperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column papers.papernames
     *
     * @mbggenerated
     */
    private String papernames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column papers.papertype
     *
     * @mbggenerated
     */
    private String papertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column papers.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column papers.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column papers.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column papers.paperid
     *
     * @return the value of papers.paperid
     *
     * @mbggenerated
     */
    public Integer getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column papers.paperid
     *
     * @param paperid the value for papers.paperid
     *
     * @mbggenerated
     */
    public void setPaperid(Integer paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column papers.papernames
     *
     * @return the value of papers.papernames
     *
     * @mbggenerated
     */
    public String getPapernames() {
        return papernames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column papers.papernames
     *
     * @param papernames the value for papers.papernames
     *
     * @mbggenerated
     */
    public void setPapernames(String papernames) {
        this.papernames = papernames == null ? null : papernames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column papers.papertype
     *
     * @return the value of papers.papertype
     *
     * @mbggenerated
     */
    public String getPapertype() {
        return papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column papers.papertype
     *
     * @param papertype the value for papers.papertype
     *
     * @mbggenerated
     */
    public void setPapertype(String papertype) {
        this.papertype = papertype == null ? null : papertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column papers.method
     *
     * @return the value of papers.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column papers.method
     *
     * @param method the value for papers.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column papers.remarks
     *
     * @return the value of papers.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column papers.remarks
     *
     * @param remarks the value for papers.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column papers.createtime
     *
     * @return the value of papers.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column papers.createtime
     *
     * @param createtime the value for papers.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }
}