package com.sz.entity;

public class Scoredata {

    @Override
    public String toString() {
        return "Scoredata{" +
                "dataid=" + dataid +
                ", scoreid=" + scoreid +
                ", eid=" + eid +
                ", uanswer='" + uanswer + '\'' +
                ", upoint=" + upoint +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredata.dataid
     *
     * @mbggenerated
     */
    private Integer dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredata.scoreid
     *
     * @mbggenerated
     */
    private Integer scoreid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredata.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredata.uanswer
     *
     * @mbggenerated
     */
    private String uanswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoredata.upoint
     *
     * @mbggenerated
     */
    private Integer upoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredata.dataid
     *
     * @return the value of scoredata.dataid
     *
     * @mbggenerated
     */
    public Integer getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredata.dataid
     *
     * @param dataid the value for scoredata.dataid
     *
     * @mbggenerated
     */
    public void setDataid(Integer dataid) {
        this.dataid = dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredata.scoreid
     *
     * @return the value of scoredata.scoreid
     *
     * @mbggenerated
     */
    public Integer getScoreid() {
        return scoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredata.scoreid
     *
     * @param scoreid the value for scoredata.scoreid
     *
     * @mbggenerated
     */
    public void setScoreid(Integer scoreid) {
        this.scoreid = scoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredata.eid
     *
     * @return the value of scoredata.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredata.eid
     *
     * @param eid the value for scoredata.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredata.uanswer
     *
     * @return the value of scoredata.uanswer
     *
     * @mbggenerated
     */
    public String getUanswer() {
        return uanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredata.uanswer
     *
     * @param uanswer the value for scoredata.uanswer
     *
     * @mbggenerated
     */
    public void setUanswer(String uanswer) {
        this.uanswer = uanswer == null ? null : uanswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoredata.upoint
     *
     * @return the value of scoredata.upoint
     *
     * @mbggenerated
     */
    public Integer getUpoint() {
        return upoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoredata.upoint
     *
     * @param upoint the value for scoredata.upoint
     *
     * @mbggenerated
     */
    public void setUpoint(Integer upoint) {
        this.upoint = upoint;
    }
}